require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hashtags_to_tweets", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HashtagsToTweet. As you add validations to HashtagsToTweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HashtagsToTweet.create! valid_attributes
      get hashtags_to_tweets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
      get hashtags_to_tweet_url(hashtags_to_tweet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hashtags_to_tweet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
      get edit_hashtags_to_tweet_url(hashtags_to_tweet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HashtagsToTweet" do
        expect {
          post hashtags_to_tweets_url, params: { hashtags_to_tweet: valid_attributes }
        }.to change(HashtagsToTweet, :count).by(1)
      end

      it "redirects to the created hashtags_to_tweet" do
        post hashtags_to_tweets_url, params: { hashtags_to_tweet: valid_attributes }
        expect(response).to redirect_to(hashtags_to_tweet_url(HashtagsToTweet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HashtagsToTweet" do
        expect {
          post hashtags_to_tweets_url, params: { hashtags_to_tweet: invalid_attributes }
        }.to change(HashtagsToTweet, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hashtags_to_tweets_url, params: { hashtags_to_tweet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hashtags_to_tweet" do
        hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
        patch hashtags_to_tweet_url(hashtags_to_tweet), params: { hashtags_to_tweet: new_attributes }
        hashtags_to_tweet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hashtags_to_tweet" do
        hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
        patch hashtags_to_tweet_url(hashtags_to_tweet), params: { hashtags_to_tweet: new_attributes }
        hashtags_to_tweet.reload
        expect(response).to redirect_to(hashtags_to_tweet_url(hashtags_to_tweet))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
        patch hashtags_to_tweet_url(hashtags_to_tweet), params: { hashtags_to_tweet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hashtags_to_tweet" do
      hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
      expect {
        delete hashtags_to_tweet_url(hashtags_to_tweet)
      }.to change(HashtagsToTweet, :count).by(-1)
    end

    it "redirects to the hashtags_to_tweets list" do
      hashtags_to_tweet = HashtagsToTweet.create! valid_attributes
      delete hashtags_to_tweet_url(hashtags_to_tweet)
      expect(response).to redirect_to(hashtags_to_tweets_url)
    end
  end
end
